using Application.Dto.Tasks;
using Application.Dto.Users;
using AutoMapper;
using Core.Entities;
using DotnetBackend.Models;
using FluentValidation;
using Infra.Repositories;
using Microsoft.AspNetCore.Mvc;

[ApiController]
[Route("api/tasks")]
[Produces("application/json")]
public class TaskController : ControllerBase
{
    private readonly IValidator<CreateTaskInput> _createValidator;
    private readonly IValidator<UpdateTaskInput> _updateValidator;
    private readonly ILogger<TaskController> _logger;
    private readonly ITaskItemRepository _taskRepository;
    private readonly IUserRepository _userRepository;
    private readonly IMapper _mapper;

    public TaskController(
        IValidator<CreateTaskInput> createValidator,
        IValidator<UpdateTaskInput> updateValidator,
        ILogger<TaskController> logger,
        ITaskItemRepository taskRepository,
        IUserRepository userRepository,
        IMapper mapper)
    {
        _createValidator = createValidator;
        _updateValidator = updateValidator;
        _logger = logger;
        _taskRepository = taskRepository;
        _userRepository = userRepository;
        _mapper = mapper;
    }

    /// <summary>
    /// Get all tasks
    /// </summary>
    [HttpGet(Name = "GetTasks")]
    [ProducesResponseType(typeof(IEnumerable<TaskItemDto>), StatusCodes.Status200OK)]
    public async Task<ActionResult<IEnumerable<TaskItemDto>>> GetTasks(
      [FromQuery] string? status = null,  // Add this parameter
      CancellationToken cancellationToken = default)
    {
        // Get all tasks
        var tasks = await _taskRepository.GetAllAsync(cancellationToken);

        // Apply status filter if provided
        if (!string.IsNullOrWhiteSpace(status))
        {
            tasks = tasks.Where(t => t.Status.Equals(status, StringComparison.OrdinalIgnoreCase));
        }
        var response = new TasksResponse
        {
            Tasks = tasks.ToList(),
            Count = tasks.Count()
        };
        return Ok(response);
    }

    /// <summary>
    /// Get task by ID
    /// </summary>
    [HttpGet("{id:int}", Name = "GetTaskById")]
    [ProducesResponseType(typeof(TaskItemDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<TaskItemDto>> GetTaskById(
        int id,
        CancellationToken cancellationToken = default)
    {
        var task = await _taskRepository.GetAsync(id, cancellationToken);

        if (task is null)
        {
            return NotFound();
        }

        var taskDto = _mapper.Map<TaskItemDto>(task);
        return Ok(taskDto);
    }

    /// <summary>
    /// Creates a new task
    /// </summary>
    [HttpPost(Name = "CreateTask")]
    [ProducesResponseType(typeof(TaskItemDto), StatusCodes.Status201Created)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> CreateTask(
        [FromBody] CreateTaskInput input,
        CancellationToken cancellationToken = default)
    {
        try
        {
            // 1. Validate request
            var validationResult = await _createValidator.ValidateAsync(input, cancellationToken);
            if (!validationResult.IsValid)
            {
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
                return ValidationProblem(ModelState);
            }

            // 2. Validate userId exists
            var userExists = await _userRepository.GetAsync(input.UserId, cancellationToken);
            if (userExists is null)
            {
                ModelState.AddModelError("UserId", $"User with ID {input.UserId} does not exist");
                return ValidationProblem(ModelState);
            }

            // 3. Map to entity (ID generated by database)
            var taskItem = _mapper.Map<TaskItem>(input);

            // 4. Create in repository
            var createdTask = await _taskRepository.CreateAsync(taskItem, cancellationToken);

            // 5. Map to DTO for response
            var taskDto = _mapper.Map<TaskItemDto>(createdTask);

            _logger.LogInformation("Task created with ID: {TaskId}", createdTask.Id);

            // 6. Return 201 with location header
            return CreatedAtAction(
                nameof(GetTaskById),
                new { id = createdTask.Id },
                taskDto);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating task");
            return Problem(
                title: "An error occurred while creating the task",
                detail: ex.Message,
                statusCode: StatusCodes.Status500InternalServerError);
        }
    }

    /// <summary>
    /// Updates an existing task (partial update)
    /// </summary>
    [HttpPut("{id:int}", Name = "UpdateTask")]
    [ProducesResponseType(typeof(TaskItemDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> UpdateTask(
        int id,
        [FromBody] UpdateTaskInput input,
        CancellationToken cancellationToken = default)
    {
        try
        {
            // 1. Check if task exists
            var existingTask = await _taskRepository.GetAsync(id, cancellationToken);
            if (existingTask is null)
            {
                return NotFound(new { error = $"Task with ID {id} not found" });
            }

            // 2. Validate request (only provided fields)
            var validationResult = await _updateValidator.ValidateAsync(input, cancellationToken);
            if (!validationResult.IsValid)
            {
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
                return ValidationProblem(ModelState);
            }

            // 3. Validate userId if provided
            if (input.UserId.HasValue)
            {
                var userExists = await _userRepository.GetAsync(input.UserId.Value, cancellationToken);
                if (userExists is null)
                {
                    ModelState.AddModelError("UserId", $"User with ID {input.UserId.Value} does not exist");
                    return ValidationProblem(ModelState);
                }
            }

            // 4. Partial update - only update provided fields
            if (!string.IsNullOrWhiteSpace(input.Title))
            {
                existingTask.Title = input.Title;
            }

            if (!string.IsNullOrWhiteSpace(input.Status))
            {
                existingTask.Status = input.Status;
            }

            if (input.UserId.HasValue)
            {
                existingTask.UserId = input.UserId.Value;
            }

            // 5. Save changes
            var updatedTask = await _taskRepository.UpdateAsync(existingTask, cancellationToken);

            // 6. Map to DTO and return
            var taskDto = _mapper.Map<TaskItemDto>(updatedTask);

            _logger.LogInformation("Task updated with ID: {TaskId}", updatedTask.Id);

            return Ok(taskDto);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error updating task {TaskId}", id);
            return Problem(
                title: "An error occurred while updating the task",
                detail: ex.Message,
                statusCode: StatusCodes.Status500InternalServerError);
        }
    }
}