using Application.Dto.Users;
using AutoMapper;
using Azure;
using Core.Entities;
using DotnetBackend.Data;
using DotnetBackend.Models;
using FluentValidation;
using Infra.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using webapi.Filters;

[ApiController]
[Route("api/users")]
[Produces("application/json")]
public class UserController : ControllerBase
{

    private readonly IValidator<CreateUserInput> _validator;
    private readonly ILogger<UserController> _logger;
    private readonly DataStore _dataStore;
    private readonly IUserRepository _userRepository;
    private readonly IMapper _mapper;
    public UserController(
        IValidator<CreateUserInput> validator,
        ILogger<UserController> logger,
        DataStore dataStore,
        IUserRepository userRepository,
        IMapper mapper)
    {
        _validator = validator;
        _logger = logger;
        _dataStore = dataStore;
        _userRepository = userRepository;
        _mapper = mapper;
    }

    [HttpGet("{id:int}", Name = "GetUserById")]
    [Cache(durationInSeconds: 300, cacheKeyPrefix: "user")] // ⭐ 5 minutes cache
    [ProducesResponseType(typeof(UserDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<UserDto>> GetUserById(
    int id,
    CancellationToken cancellationToken = default)
    {
        var user = await _userRepository.GetAsync(id, cancellationToken);

        if (user is null)
        {
            return NotFound();
        }

        var userDto = _mapper.Map<UserDto>(user);
        return Ok(userDto);
    }


    [HttpGet(Name = "users")]
    [Cache(durationInSeconds: 600, cacheKeyPrefix: "user")] // ⭐ 10 minutes cache
    public async Task<IActionResult> Users(CancellationToken cancellationToken = default)
    {
        var users = await _userRepository.GetAllAsync(cancellationToken);
        var response = new UsersResponse
        {
            Users = users.ToList(),
            Count = users.Count()
        };
        return Ok(response);
    }


    ///// <summary>
    ///// Creates a new user
    ///// </summary>
    ///// <param name="input">User creation details</param>
    ///// <returns>The created user</returns>
    ///// <response code="201">Returns the newly created user</response>
    ///// <response code="400">If the request is invalid</response>
    ///// <response code="500">If there was an internal server error</response>
    [HttpPost(Name = "users")]
    [ProducesResponseType(typeof(UserDto), StatusCodes.Status201Created)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> Users(CreateUserInput input,CancellationToken cancellationToken = default)
    {
        try
        {
            // Validate request
            var validationResult = await _validator.ValidateAsync(input);
            if (!validationResult.IsValid)
            {
                var errorMessages = validationResult.Errors.Select(s => s.ErrorMessage).ToList();
                ModelState.AddModelError("Email", string.Join(", " , errorMessages));
                return ValidationProblem(ModelState); 
            }

            // Check for duplicate email
            if ((await _userRepository.GetAllAsync()).Any(u => u.Email.Equals(input.Email, StringComparison.OrdinalIgnoreCase)))
            {
                ModelState.AddModelError("Email", "Email already exists");
                return ValidationProblem(ModelState);
            }

            // 3. Map to entity (ID generated by database)
            var user = _mapper.Map<User>(input);

            // 4. Create in repository
            var createdUser = await _userRepository.CreateAsync(user, cancellationToken);

            // 5. Map to DTO for response
            var userDto = _mapper.Map<UserDto>(createdUser);

            _logger.LogInformation("User created with ID: {UserId}", createdUser.Id);

            // 6. Return 201 with location header
            return CreatedAtAction(nameof(Users), new { id = user.Id }, userDto);

        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating user");
            return Problem(
                title: "An error occurred while creating the user",
                detail: "Please try again later",
                statusCode: StatusCodes.Status500InternalServerError
            );
        }

    }


}

